# this was produced by calling kaggle_to_collected(2011) and then manually fixing it by looking at
#   http://en.wikipedia.org/wiki/List_of_colloquial_names_for_universities_and_colleges_in_the_United_States
# For schools for which I didn't find the matching the value is None

kaggle_to_collected = {
    'Abilene Chr': u'Abilene Christian Wildcats',
    'Air Force': u'Air Force Falcons',
    'Akron': u'Akron Zips',
    'Alabama': u'Alabama Crimson Tide',
    'Alabama A&M': u'Alabama A&M Bulldogs',
    'Alabama St': u'Alabama State Hornets',
    'Albany NY': u'Albany (NY) Great Danes',
    'Alcorn St': u'Alcorn State Braves',
    'Alliant Intl': None, #u'Alliant International Gulls',
    'American Univ': u'American Eagles',
    'Appalachian St': u'Appalachian State Mountaineers',
    'Arizona': u'Arizona Wildcats',
    'Arizona St': u'Arizona State Sun Devils',
    'Ark Little Rock': u'Arkansas-Little Rock Trojans',
    'Ark Pine Bluff': u'Arkansas-Pine Bluff Golden Lions',
    'Arkansas': u'Arkansas Razorbacks',
    'Arkansas St': u'Arkansas State Red Wolves',
    'UT Arlington': u'Texas-Arlington Mavericks',
    'Armstrong St': None, #u'Armstrong Pirates',
    'Army': u'Army Black Knights',
    'Auburn': u'Auburn Tigers',
    'Augusta': None, #u'Augusta State Jaguars',
    'Austin Peay': u'Austin Peay Governors',
    'BYU': u'Brigham Young Cougars',
    'Ball St': u'Ball State Cardinals',
    'Baylor': u'Baylor Bears',
    'Belmont': u'Belmont Bruins',
    'Bethune-Cookman': u'Bethune-Cookman Wildcats',
    'Binghamton': u'Binghamton Bearcats',
    'Birmingham So': None,
    'Boise St': u'Boise State Broncos',
    'Boston College': u'Boston College Eagles',
    'Boston Univ': u'Boston University Terriers',
    'Bowling Green': u'Bowling Green State Falcons',
    'Bradley': u'Bradley Braves',
    'Brooklyn': None, #u'Brooklyn Bulldogs',
    'Brown': u'Brown Bears',
    'Bryant': u'Bryant Bulldogs',
    'Bucknell': u'Bucknell Bison',
    'Buffalo': u'Buffalo Bulls',
    'Butler': u'Butler Bulldogs',
    'C Michigan': u'Central Michigan Chippewas',
    'CS Bakersfield': u'Cal State Bakersfield Roadrunners',
    'CS Fullerton': u'Cal State Fullerton Titans',
    'CS Northridge': u'Cal State Northridge Matadors',
    'CS Sacramento': u'Sacramento State Hornets',
    'Cal Poly SLO': u'Cal Poly Mustangs',
    'California': u'University of California Golden Bears',
    'Campbell': u'Campbell Fighting Camels',
    'Canisius': u'Canisius Golden Griffins',
    'Cent Arkansas': u'Central Arkansas Bears',
    'Centenary': u'Centenary (LA) Gents',
    'Central Conn': u'Central Connecticut State Blue Devils',
    'Charleston So': u'Charleston Southern Buccaneers',
    'Charlotte': u'Charlotte 49ers',
    'Chattanooga': u'Chattanooga Mocs',
    'Chicago St': u'Chicago State Cougars',
    'Cincinnati': u'Cincinnati Bearcats',
    'Citadel': u'Citadel Bulldogs',
    'Clemson': u'Clemson Tigers',
    'Cleveland St': u'Cleveland State Vikings',
    'Coastal Car': u'Coastal Carolina Chanticleers',
    'Col Charleston': u'College of Charleston Cougars',
    'Colgate': u'Colgate Raiders',
    'Colorado': u'Colorado Buffaloes',
    'Colorado St': u'Colorado State Rams',
    'Columbia': u'Columbia Lions',
    'Connecticut': u'Connecticut Huskies',
    'Coppin St': u'Coppin State Eagles',
    'Cornell': u'Cornell Big Red',
    'Creighton': u'Creighton Bluejays',
    'Dartmouth': u'Dartmouth Big Green',
    'Davidson': u'Davidson Wildcats',
    'Dayton': u'Dayton Flyers',
    'DePaul': u'DePaul Blue Demons',
    'Delaware': u"Delaware Fightin' Blue Hens",
    'Delaware St': u'Delaware State Hornets',
    'Denver': u'Denver Pioneers',
    'Detroit': u'Detroit Mercy Titans',
    'Drake': u'Drake Bulldogs',
    'Drexel': u'Drexel Dragons',
    'Duke': u'Duke Blue Devils',
    'Duquesne': u'Duquesne Dukes',
    'E Illinois': u'Eastern Illinois Panthers',
    'E Kentucky': u'Eastern Kentucky Colonels',
    'E Michigan': u'Eastern Michigan Eagles',
    'E Washington': u'Eastern Washington Eagles',
    'ETSU': u'East Tennessee State Buccaneers',
    'East Carolina': u'East Carolina Pirates',
    'Edwardsville': u'Southern Illinois-Edwardsville Cougars',
    'Elon': u'Elon Phoenix',
    'Evansville': u'Evansville Purple Aces',
    'F Dickinson': u'Fairleigh Dickinson Knights',
    'FL Atlantic': u'Florida Atlantic Owls',
    'FL Gulf Coast': u'Florida Gulf Coast Eagles',
    'Fairfield': u'Fairfield Stags',
    'Florida': u'Florida Gators',
    'Florida A&M': u'Florida A&M Rattlers',
    'Florida Intl': u'Florida International Panthers',
    'Florida St': u'Florida State Seminoles',
    'Fordham': u'Fordham Rams',
    'Fresno St': u'Fresno State Bulldogs',
    'Furman': u'Furman Paladins',
    'G Washington': u'George Washington Colonials',
    'Ga Southern': u'Georgia Southern Eagles',
    'Gardner Webb': u"Gardner-Webb Runnin' Bulldogs",
    'George Mason': u'George Mason Patriots',
    'Georgetown': u'Georgetown Hoyas',
    'Georgia': u'Georgia Bulldogs',
    'Georgia St': u'Georgia State Panthers',
    'Georgia Tech': u'Georgia Tech Yellow Jackets',
    'Gonzaga': u'Gonzaga Bulldogs',
    'Grambling': u'Grambling Tigers',
    'Grand Canyon': u'Grand Canyon Antelopes',
    'WI Green Bay': u'Green Bay Phoenix',
    'Hampton': u'Hampton Pirates',
    'Hardin-Simmons': None,
    'Hartford': u'Hartford Hawks',
    'Harvard': u'Harvard Crimson',
    'Hawaii': u'Hawaii Warriors',
    'High Point': u'High Point Panthers',
    'Hofstra': u'Hofstra Pride',
    'Holy Cross': u'Holy Cross Crusaders',
    'Houston': u'Houston Cougars',
    'Houston Bap': u'Houston Baptist Huskies',
    'Howard': u'Howard Bison',
    'IL Chicago': u'Illinois-Chicago Flames',
    'IPFW': u'IPFW Mastodons',
    'IUPUI': u'IUPUI Jaguars',
    'Idaho': u'Idaho Vandals',
    'Idaho St': u'Idaho State Bengals',
    'Illinois': u'Illinois Fighting Illini',
    'Illinois St': u'Illinois State Redbirds',
    'Incarnate Word': u'Incarnate Word Cardinals',
    'Indiana': u'Indiana Hoosiers',
    'Indiana St': u'Indiana State Sycamores',
    'Iona': u'Iona Gaels',
    'Iowa': u'Iowa Hawkeyes',
    'Iowa St': u'Iowa State Cyclones',
    'Jackson St': u'Jackson State Tigers',
    'Jacksonville': u'Jacksonville Dolphins',
    'Jacksonville St': u'Jacksonville State Gamecocks',
    'James Madison': u'James Madison Dukes',
    'Kansas': u'Kansas Jayhawks',
    'Kansas St': u'Kansas State Wildcats',
    'Kennesaw': u'Kennesaw State Owls',
    'Kent': u'Kent State Golden Flashes',
    'Kentucky': u'Kentucky Wildcats',
    'LSU': u'Louisiana State Fighting Tigers',
    'La Salle': u'La Salle Explorers',
    'Lafayette': u'Lafayette Leopards',
    'Lamar': u'Lamar Cardinals',
    'Lehigh': u'Lehigh Mountain Hawks',
    'Liberty': u'Liberty Flames',
    'Lipscomb': u'Lipscomb Bisons',
    'Long Beach St': u'Long Beach State 49ers',
    'Long Island': u'Long Island University Blackbirds',
    'Longwood': u'Longwood Lancers',
    'Louisiana Tech': u'Louisiana Tech Bulldogs',
    'Louisville': u'Louisville Cardinals',
    'Loy Marymount': u'Loyola Marymount Lions',
    'Loyola MD': u'Loyola (MD) Greyhounds',
    'Loyola-Chicago': u'Loyola (IL) Ramblers',
    'MA Lowell': u'Massachusetts-Lowell River Hawks',
    'MD E Shore': u'Maryland-Eastern Shore Hawks',
    'MS Valley St': u'Mississippi Valley State Delta Devils',
    'MTSU': u'Middle Tennessee Blue Raiders',
    'Maine': u'Maine Black Bears',
    'Manhattan': u'Manhattan Jaspers',
    'Marist': u'Marist Red Foxes',
    'Marquette': u'Marquette Golden Eagles',
    'Marshall': u'Marshall Thundering Herd',
    'Maryland': u'Maryland Terrapins',
    'Massachusetts': u'Massachusetts Minutemen',
    'McNeese St': u'McNeese State Cowboys',
    'Memphis': u'Memphis Tigers',
    'Mercer': u'Mercer Bears',
    'Miami FL': u'Miami (FL) Hurricanes',
    'Miami OH': u'Miami (OH) RedHawks',
    'Michigan': u'Michigan Wolverines',
    'Michigan St': u'Michigan State Spartans',
    'WI Milwaukee': u'Milwaukee Panthers',
    'Minnesota': u'Minnesota Golden Gophers',
    'Mississippi': u'Mississippi Rebels',
    'Mississippi St': u'Mississippi State Bulldogs',
    'Missouri': u'Missouri Tigers',
    'Missouri KC': u'Missouri-Kansas City Kangaroos',
    'Missouri St': u'Missouri State Bears',
    'Monmouth NJ': u'Monmouth Hawks',
    'Montana': u'Montana Grizzlies',
    'Montana St': u'Montana State Bobcats',
    'Morehead St': u'Morehead State Eagles',
    'Morgan St': u'Morgan State Bears',
    'Morris Brown': None, #u'Morris Brown Wolverines',
    "Mt St Mary's": u"Mount St. Mary's Mountaineers",
    'Murray St': u'Murray State Racers',
    'N Colorado': u'Northern Colorado Bears',
    'N Dakota St': u'North Dakota State Bison',
    'N Illinois': u'Northern Illinois Huskies',
    'N Kentucky': u'Northern Kentucky Norse',
    'NC A&T': u'North Carolina A&T Aggies',
    'NC Central': u'North Carolina Central Eagles',
    'NC State': u'North Carolina State Wolfpack',
    'NE Illinois': None, #u'Northeastern Illinois Golden Eagles',
    'NE Omaha': u'Nebraska-Omaha Mavericks',
    'NJIT': u'NJIT Highlanders',
    'Navy': u'Navy Midshipmen',
    'Nebraska': u'Nebraska Cornhuskers',
    'Nevada': u'Nevada Wolf Pack',
    'New Hampshire': u'New Hampshire Wildcats',
    'New Mexico': u'New Mexico Lobos',
    'New Mexico St': u'New Mexico State Aggies',
    'New Orleans': u'New Orleans Privateers',
    'Niagara': u'Niagara Purple Eagles',
    'Nicholls St': u'Nicholls State Colonels',
    'Norfolk St': u'Norfolk State Spartans',
    'North Carolina': u'North Carolina Tar Heels',
    'North Dakota': u'North Dakota UND',
    'North Florida': u'North Florida Ospreys',
    'North Texas': u'North Texas Mean Green',
    'Northeastern': u'Northeastern Huskies',
    'Northern Arizona': u'Northern Arizona Lumberjacks',
    'Northern Iowa': u'Northern Iowa Panthers',
    'Northwestern': u'Northwestern Wildcats',
    'Northwestern LA': u'Northwestern State Demons',
    'Notre Dame': u'Notre Dame Fighting Irish',
    'Oakland': u'Oakland Golden Grizzlies',
    'Ohio': u'Ohio Bobcats',
    'Ohio St': u'Ohio State Buckeyes',
    'Okla City': None, #u'Oklahoma City Chiefs',
    'Oklahoma': u'Oklahoma Sooners',
    'Oklahoma St': u'Oklahoma State Cowboys',
    'Old Dominion': u'Old Dominion Monarchs',
    'Oral Roberts': u'Oral Roberts Golden Eagles',
    'Oregon': u'Oregon Ducks',
    'Oregon St': u'Oregon State Beavers',
    'Pacific': u'Pacific Tigers',
    'Penn': u'Pennsylvania Quakers',
    'Penn St': u'Penn State Nittany Lions',
    'Pepperdine': u'Pepperdine Waves',
    'Pittsburgh': u'Pittsburgh Panthers',
    'Portland': u'Portland Pilots',
    'Portland St': u'Portland State Vikings',
    'Prairie View': u'Prairie View Panthers',
    'Presbyterian': u'Presbyterian Blue Hose',
    'Princeton': u'Princeton Tigers',
    'Providence': u'Providence Friars',
    'Purdue': u'Purdue Boilermakers',
    'Quinnipiac': u'Quinnipiac Bobcats',
    'Radford': u'Radford Highlanders',
    'Rhode Island': u'Rhode Island Rams',
    'Rice': u'Rice Owls',
    'Richmond': u'Richmond Spiders',
    'Rider': u'Rider Broncs',
    'Robert Morris': u'Robert Morris Colonials',
    'Rutgers': u'Rutgers Scarlet Knights',
    'S Carolina St': u'South Carolina State Bulldogs',
    'S Dakota St': u'South Dakota State Jackrabbits',
    'S Illinois': u'Southern Illinois Salukis',
    'SC Upstate': u'South Carolina Upstate Spartans',
    'SE Louisiana': u'Southeastern Louisiana Lions',
    'SE Missouri St': u'Southeast Missouri State Redhawks',
    'SF Austin': u'Stephen F. Austin Lumberjacks',
    'SMU': u'Southern Methodist Mustangs',
    'Sacred Heart': u'Sacred Heart Pioneers',
    'Sam Houston St': u'Sam Houston State Bearkats',
    'Samford': u'Samford Bulldogs',
    'UT San Antonio': u'Texas-San Antonio Roadrunners',
    'San Diego': u'San Diego Toreros',
    'San Diego St': u'San Diego State Aztecs',
    'San Francisco': u'San Francisco Dons',
    'San Jose St': u'San Jose State Spartans',
    'Santa Barbara': u'UC-Santa Barbara Gauchos',
    'Santa Clara': u'Santa Clara Broncos',
    'Savannah St': u'Savannah State Tigers',
    'Seattle': u'Seattle Redhawks',
    'Seton Hall': u'Seton Hall Pirates',
    'Siena': u'Siena Saints',
    'South Alabama': u'South Alabama Jaguars',
    'South Carolina': u'South Carolina Gamecocks',
    'South Dakota': u'South Dakota Coyotes',
    'South Florida': u'South Florida Bulls',
    'Southern Miss': u'Southern Mississippi Golden Eagles',
    'Southern Univ': u'Southern Jaguars',
    'Southern Utah': u'Southern Utah Thunderbirds',
    'St Bonaventure': u'St. Bonaventure Bonnies',
    'St Francis NY': u'St. Francis (NY) Terriers',
    'St Francis PA': u'Saint Francis (PA) Red Flash',
    "St John's": u"St. John's (NY) Red Storm",
    "St Joseph's PA": u"Saint Joseph's Hawks",
    'St Louis': u'Saint Louis Billikens',
    "St Mary's CA": u"Saint Mary's (CA) Gaels",
    "St Peter's": u"Saint Peter's Peacocks",
    'Stanford': u'Stanford Cardinal',
    'Stetson': u'Stetson Hatters',
    'Stony Brook': u'Stony Brook Seawolves',
    'Syracuse': u'Syracuse Orange',
    'TAM C. Christi': u'Texas A&M-Corpus Christi Islanders',
    'TCU': u'Texas Christian Horned Frogs',
    'TN Martin': u'Tennessee-Martin Skyhawks',
    'TX Pan American': u'Texas-Rio Grande Valley Vaqueros',
    'TX Southern': u'Texas Southern Tigers',
    'Temple': u'Temple Owls',
    'Tennessee': u'Tennessee Volunteers',
    'Tennessee St': u'Tennessee State Tigers',
    'Tennessee Tech': u'Tennessee Tech Golden Eagles',
    'Texas': u'Texas Longhorns',
    'Texas A&M': u'Texas A&M Aggies',
    'Texas St': u'Texas State Bobcats',
    'Texas Tech': u'Texas Tech Red Raiders',
    'Toledo': u'Toledo Rockets',
    'Towson': u'Towson Tigers',
    'Troy': u'Troy Trojans',
    'Tulane': u'Tulane Green Wave',
    'Tulsa': u'Tulsa Golden Hurricane',
    'UAB': u'Alabama-Birmingham Blazers',
    'UC Davis': u'UC-Davis Aggies',
    'UC Irvine': u'UC-Irvine Anteaters',
    'UC Riverside': u'UC-Riverside Highlanders',
    'UCF': u'Central Florida Knights',
    'UCLA': u'UCLA Bruins',
    'ULL': None,
    'ULM': u'Louisiana-Monroe Warhawks',
    'UMBC': u'Maryland-Baltimore County Retrievers',
    'UNC Asheville': u'North Carolina-Asheville Bulldogs',
    'UNC Greensboro': u'North Carolina-Greensboro Spartans',
    'UNC Wilmington': u'North Carolina-Wilmington Seahawks',
    'UNLV': u'Nevada-Las Vegas Rebels',
    'USC': u'South Carolina Upstate Spartans',
    'UTEP': u'Texas-El Paso Miners',
    'Utah': u'Utah Utes',
    'Utah St': u'Utah State Aggies',
    'Utah Valley': u'Utah Valley Wolverines',
    'Utica': None,
    'VA Commonwealth': u'Virginia Commonwealth Rams',
    'VMI': u'Virginia Military Institute Keydets',
    'Valparaiso': u'Valparaiso Crusaders',
    'Vanderbilt': u'Vanderbilt Commodores',
    'Vermont': u'Vermont Catamounts',
    'Villanova': u'Villanova Wildcats',
    'Virginia': u'Virginia Cavaliers',
    'Virginia Tech': u'Virginia Tech Hokies',
    'Wagner': u'Wagner Seahawks',
    'Wake Forest': u'Wake Forest Demon Deacons',
    'Washington': u'Washington Huskies',
    'Washington St': u'Washington State Cougars',
    'Weber St': u'Weber State Wildcats',
    'West Virginia': u'West Virginia Mountaineers',
    'W Carolina': u'Western Carolina Catamounts',
    'W Illinois': u'Western Illinois Leathernecks',
    'W Kentucky': u'Western Kentucky Hilltoppers',
    'W Michigan': u'Western Michigan Broncos',
    'W Salem St': None,
    'W Texas A&M': None, #u'West Texas A&M Buffaloes',
    'Wichita St': u'Wichita State Shockers',
    'William & Mary': u'William & Mary Tribe',
    'Winthrop': u'Winthrop Eagles',
    'Wisconsin': u'Wisconsin Badgers',
    'Wofford': u'Wofford Terriers',
    'Wright St': u'Wright State Raiders',
    'Wyoming': u'Wyoming Cowboys',
    'Xavier': u'Xavier Musketeers',
    'Yale': u'Yale Bulldogs',
    'Youngstown St': u'Youngstown State Penguins'}